name: virtual_traveller_flutter
description: Travel virtually and discover interesting destinations.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.27.0-0" # this constraint is needed for integration tests, may be removed

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.0 # https://pub.dev/packages/http
  rxdart: ^0.26.0-nullsafety.1 # https://pub.dev/packages/rxdart https://rxmarbles.com/
  equatable: ^2.0.0-nullsafety.3 # https://pub.dev/packages/equatable
  flutter_bloc: ^7.0.0-nullsafety.2 # https://pub.dev/packages/flutter_bloc https://bloclibrary.dev/#/
  bloc_test: ^8.0.0-nullsafety.0 # https://pub.dev/packages/bloc_test
  mockito: ^5.0.0 # https://pub.dev/packages/mockito
  freezed: ^0.13.0-nullsafety.2 # https://pub.dev/packages/freezed
  json_serializable: ^4.0.1 # https://pub.dev/packages/json_serializable
  shared_preferences: ^2.0.0 # https://pub.dev/packages/shared_preferences
  url_launcher: ^6.0.0 # https://pub.dev/packages/url_launcher
#  geolocator: ^7.0.1 # https://pub.dev/packages/geolocator

  # ui related
  clean_settings_nnbd: ^0.1.0 # https://pub.dev/packages/clean_settings_nnbd
  flutter_typeahead: ^3.0.0-nullsafety.0 # https://pub.dev/packages/flutter_typeahead
  shimmer: ^2.0.0-nullsafety.0 # https://pub.dev/packages/shimmer
  flutter_svg: ^0.21.0-nullsafety.0 # https://pub.dev/packages/flutter_svg
#  animations: ^1.1.2 # https://pub.dev/packages/animations


# flutter pub run build_runner build --delete-conflicting-outputs
# flutter pub run build_runner watch
dev_dependencies:
  flutter_test:
    sdk: flutter
  test: any
  flutter_driver:
    sdk: flutter
  pedantic: ^1.10.0 # https://pub.dev/packages/pedantic
  build_runner: ^1.11.5 # https://pub.dev/packages/build_runner

dependency_overrides:
  analyzer: '1.0.0'

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
